# Tensor
tensor is a generalization of vectors and matrices to potentially higher dimensions
- each tensor has a data type and a shape
- Data types include: **float32**, **int32**, **string**, and **more**

In [5]:
import tensorflow as tf

## Creating tensors:

In [6]:
string = tf.Variable('This is a string', tf.string)
number = tf.Variable(324, tf.int32)
floating = tf.Variable(3.456, tf.float32)

## Rank/Degree
Another word for **rank** is **degree**
- this means the number of **dimensions** involved in the tesnor
- Above is a scalar of rank 0 (singular dimension)

In [8]:
rank1_tensor = tf.Variable(['test', 'ok'], tf.string)
rank2_tensor = tf.Variable([['test', 'ok'], ['test', 'ok']], tf.string)

### to determine rank

In [9]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of tensors

In [10]:
rank2_tensor.shape

TensorShape([2, 2])

## Changing shape


In [11]:
tensor1 = tf.ones([1, 2, 3]) # creates a [1, 2, 3] shape tesnor full of ones
tensor2 = tf.reshape(tensor1, [2, 3, 1]) # reshapes tensor
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of dimensions in that place
print('tensor1: ', tensor1)
print('tensor2: ', tensor2)
print('tensor3: ', tensor3)

tensor1:  tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tensor2:  tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tensor3:  tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of tensors:
- Variable
- Constant
- Placeholder
- SparseTensor

Note: With the exception of Variable, tensors are immutable

# Evaluating Tensors

In [ ]:
with tf.Session() as sess: # creates a session using the default graph
    tensor.eval() # {tensor} is name of the tensor